### ISSUE TITLE
No way to delete or edit events

### ISSUE THREAD

**Issue by zacharylove** [delexagon/executive-planner#2]
Currently, there is no way to delete or edit Events once they are made. 

**Deleting:** Double-clicking an event in the event list will make it disappear, but navigating back to the list or refreshing will reveal that the Event is still there.
**Editing:** Although the Event creation page does have functionality for editing events, there is currently no way to open that page for a previously created event.

Need to fix the event deletion for swiping/double-clicking, and add a button to the event list that allows the user to edit previously-created events.

**Comment by delexagon** [comment]
Removing and changing events is currently done by holding left click on the event; double tapping should not remove it. EventChangeForm supports that functionality. Events returning after being marked as complete should _not_ occur, they should only be visible via search. I should probably delete them after a set amount of time and make them more visible somehow.

**Comment by delexagon** [comment]
Refreshing returns the event because I haven’t added JSON to store tags to browser data yet.

**Comment by delexagon** [comment]
I added the Jason
