### ISSUE TITLE
Intermittent crashes while testing

### ISSUE THREAD

**Issue by zacharylove** [delexagon/executive-planner#3]
While running in debug mode, the project will sometimes crash when rebuilding, with the error attributed to `_$Event.fromJson`'s `checkKeys` failing.
<img width="636" alt="image" src="https://user-images.githubusercontent.com/12072877/160673353-6c64cfc9-a465-4afb-82b9-ab00af9ffdc0.png">
Likely due to `FileStorage.readFile` returning a `dynamic` object (not a `Map<String, dynamic>`) with no `String`

**Comment by delexagon** [comment]
JSON is now removed entirely, so this should no longer occur.
